app/controllers/application_controller.rb, app/controllers/favorites_controller.rb, app/controllers/pets_controller.rb, app/models/favorite.rb, app/views/layouts/application.html.erb, app/views/pets/edit.html.erb, app/views/pets/index.html.erb, app/views/pets/new.html.erb, app/views/pets/show.html.erb, app/views/shelter_pets/index.html.erb, app/views/shelters/edit.html.erb, app/views/shelters/index.html.erb, app/views/shelters/new.html.erb, app/views/shelters/show.html.erb, config/routes.rb, spec/features/favorites/add_favorite_spec.rb, spec/models/favorite_spec.rb
Add Favorite Pet:
* Add a feature spec for adding favorite pet
* Add Favorite class with total_count, add_pet, and count_of methods
* Add FavoritesController and add update action
* Add patch route directed to FavoritesController
* Add number of favorited pets to nav bar
* Moved navbar to application.html.erb and removed from the top of all pages
All tests passing
=> Favorite creation

app/controllers/shelters_controller.rb, app/models/review.rb, app/models/shelter.rb, app/views/shelters/show.html.erb, db/migrate/20200512042141_create_reviews.rb, db/migrate/20200512042533_add_shelter_to_reviews.rb, db/schema.rb, db/seeds.rb, spec/factories/review.rb, spec/features/user_sees_all_shelter_reviews_spec.rb, spec/models/review_spec.rb, spec/models/shelter_spec.rb
Add Shelter Reviews table
Add a feature spec for seeing shelter reviews
Add a model spec for connecting to the reviews table
Add reviews class
Add created reviews to seed folder
Fixed merge conflicts
All tests passing
=> User story 2

app/controllers/favorites_controller.rb, app/views/favorites/index.html.erb, app/views/layouts/application.html.erb, config/routes.rb, spec/features/favorites/see_favorite_spec.rb
Add Favorite Pet Index
* Add a feature spec for seeing favorite pets
* Add get route and index action method
* Add link in number of favorited pets in nav bar to favorites index
* All tests passing
=> User Stories 10 and 11

app/controllers/reviews_controller.rb, app/views/reviews/new.html.erb, app/views/shelters/show.html.erb, config/routes.rb, spec/features/user_creates_review_spec.rb
Add Review Create
Add a feature spec for creating shelter reviews
Add get route and create action method
Add reviews_controller with methods create and new
Add new review view 
Add image optional field
All tests passing except one( "Favorited Pets"),  Derek planning to fix in next pull request.
=> User story 3

app/assets/stylesheets/application.css, app/views/favorites/index.html.erb, app/views/layouts/application.html.erb, app/views/pets/edit.html.erb, app/views/pets/index.html.erb, app/views/pets/new.html.erb, app/views/pets/show.html.erb, app/views/reviews/new.html.erb, app/views/shelter_pets/index.html.erb, app/views/shelters/edit.html.erb, app/views/shelters/index.html.erb, app/views/shelters/new.html.erb, app/views/shelters/show.html.erb, spec/features/favorites/delete_favorite_spec.rb, spec/features/favorites/see_favorite_spec.rb
Update view for all pages:
* Objects populated into views now sort into columns across the page instead of just being listed vertically. 
* Headers are now centered across page better
=> All views update

app/controllers/pet_applications_controller.rb, app/controllers/pets_controller.rb, app/models/application.rb, app/views/applications/show.html.erb, app/views/pets/show.html.erb, config/routes.rb, spec/features/applications/approve_application_spec.rb, spec/features/applications/show_application_spec.rb, spec/models/application_spec.rb
Adds approve application:
* Adds spec for application approve
* Adds application update link, route, and update_approval action method
* Updates pet show view to include who has applied for pet
* Adds approved_application model method
=> User story22

app/views/pets/show.html.erb
-Updated pets show page 
-If pet does not have an approved application,  it will no longer cause errors.
-all tests passing
=> Add fixes to pets show page

app/controllers/pet_applications_controller.rb, spec/features/applications/approve_application_spec.rb, spec/features/applications/approve_multiple_spec.rb
-Add pets can only have one approved application at any given time. 
-Add updates to feature test approve_application_spec 
-Add flash message to pet_application controller 
-All tests passing
=> User story24

app/controllers/applications_controller.rb, app/controllers/pet_applications_controller.rb, app/models/application.rb, app/models/pet_application.rb, app/views/applications/show.html.erb, app/views/pets/show.html.erb, config/routes.rb, db/migrate/20200517165501_remove_approval_status_from_applications.rb, db/migrate/20200517170318_remove_approved_from_pet_applications.rb, db/migrate/20200517170429_add_approved_to_pet_applications.rb, db/schema.rb, spec/factories/application.rb, spec/features/applications/approve_application_spec.rb, spec/features/applications/approve_multiple_spec.rb, spec/features/applications/create_application_spec.rb, spec/features/applications/show_application_spec.rb, spec/models/application_spec.rb, spec/models/pet_application_spec.rb
-Add approved applications can be revoked
-Add updates to approve_applications_spec
-Add "unapprove" button for previously approved applications on applications show page 
-Add pet_applications controller method "destroy approval"
-Remove applications approval statuses from applications, moved to pet_applications 
-Add model testing for pet_applications 
-All tests passing
=> User story25

app/controllers/pet_applications_controller.rb, spec/features/applications/approve_application_spec.rb
-Update rspec test in approve_application_spec
-Removed expectation for flash message, added expectation for no approve link.
=> Remove flash message

app/controllers/shelters_controller.rb, app/models/shelter.rb, db/seeds.rb, spec/features/applications/approve_application_spec.rb, spec/features/shelters/shelter_and_reviews_delete_spec.rb, spec/features/user_creates_new_shelter_spec.rb, spec/features/user_updates_shelter_spec.rb
Reviews
* When shelters are deleted, all of its reviews are also now deleted.
Modify shelter create and update
* Adds specs for creating and updating shelters with incomplete info
* Add flash messages in create and update actions in shelters controller
=> User Stories 28 & 29

app/views/pets/index.html.erb, app/views/pets/show.html.erb, spec/features/pets/user_cannot_delete_pet_with_approved_app_spec.rb, spec/features/pets/user_deletes_pet_deletes_favorit_spec.rb
-Add pets with approved applications cannot be deleted
-Add new rspec folder and file
-Add if statement to pets show page and pets index page
-Add Deleting a pet it removes it from favorites 
-Create spec for deleting favorited pets
=> User story 31 & 32

app/models/pet.rb, app/views/shelters/index.html.erb, app/views/shelters/show.html.erb, spec/features/shelters/approved_pets_delete_spec.rb, spec/models/pet_spec.rb
* Add pets_with_pending_status model method
* Add method in shelter show and shelter index to prevent shelters with pets with pending adoption status from being deleted.
=> Additions to user stories 26 & 27

app/views/pet_applications/index.html.erb, app/views/pets/show.html.erb, spec/features/applications/user_sees_applicant_name_as_link_spec.rb, spec/features/pets/user_sees_link_for_each_pet_name_spec.rb, spec/features/shelters/user_sees_link_for_every_shelter_name_spec.rb
Add every shelter name is a shelter show page link
-Was already implemented, just wrote tests.
Add every pet name is a pet show page link
-Add rspec file
-Add functionality to pet application index page
Add applicant name is link to application show page
-Add rspec file
-Add link to pets show page, when application is "on hold" for applicant
=> User story 34,35, & 36

app/models/pet.rb, app/models/review.rb, app/views/shelters/show.html.erb, spec/features/shelters/shelter_statistics_spec.rb, spec/models/pet_spec.rb, spec/models/review_spec.rb
Add shelter statistics on shelter show page:
* Count of pets that are at the shelter
* Average review rating for shelter
* Number of applications on file for pets at the shelter
* Add number_of_apps pet model method
* Add average_rating review model method
=> Shelter statistics

app/models/pet.rb, app/views/favorites/index.html.erb, spec/features/favorites/see_favorite_spec.rb, spec/models/pet_spec.rb
Add pets with approved applications to favorites index page:
* Add pets_with_unapproved_apps model method and spec
* Updated pets_with_unapproved_apps model method and spec
* Pets now only display once if they have more than one application on them
=> User Story 37

app/views/pets/index.html.erb, app/views/reviews/new.html.erb, app/views/shelter_pets/index.html.erb, spec/features/pets/user_cannot_delete_pet_with_approved_app_spec.rb
-Add updates to shelter pets index page 
-Pets with approved applications will no longer have delete buttons
-Add rspec test
=> Pet Index Fix

app/controllers/shelters_controller.rb, app/views/shelters/_form.html.erb, app/views/shelters/edit.html.erb, app/views/shelters/new.html.erb, spec/features/shelters/user_updates_shelter_spec.rb
* Add _form.html.erb with shelter form template
* Render form partial in edit and new views
All tests passing
=> Shelter partials

Gemfile, Gemfile.lock, app/models/shelter.rb, app/views/shelters/index.html.erb, spec/features/shelters/user_sees_all_shelters_spec.rb, spec/models/shelter_spec.rb
* Add top 3 highest rated shelters to shelter index and spec
* Add three_highest_rated shelter model method and spec
All tests passing
=> User Story 40

app/controllers/reviews_controller.rb, app/models/review.rb, app/views/reviews/edit.html.erb, app/views/reviews/new.html.erb, spec/factories/review.rb, spec/features/reviews/user_creates_review_spec.rb, spec/models/review_spec.rb
-Add model test for validate_inclusion of review rating range 1-10
-Add validation to review model for range 1-10
-Add factory bot limit for creating review ratings
-Add feature test for default image on create review form
-Update reviews_controller with if statement in params for default img_url
=> User Story 38 and adding (1-10) limit to rating

app/controllers/shelters_controller.rb, app/models/review.rb, app/views/shelters/show.html.erb, spec/features/reviews/user_can_edit_shelter_reviews_spec.rb, spec/models/review_spec.rb
Added sortable reviews
* Add model methods for sorting reviews
* Update shelter show
=> Sortable reviews

app/controllers/reviews_controller.rb, app/views/layouts/application.html.erb, app/views/shelters/show.html.erb, spec/features/reviews/user_can_edit_shelter_reviews_spec.rb, spec/features/reviews/user_creates_review_spec.rb
Small cosmetic changes. Updated review flash messages.
=> Refactorv2

app/views/applications/show.html.erb
- Remove unnaprove pet button from pet applications with approved pets elsewhere.
=> Update unnaprove pet button on applications
